# Fabric
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
fabric_api_version=0.116.17+1.21.1

# ParchmentMC
parchment_version=2024.11.17

# Mod
mod_version=1.0.0
maven_group=dev.iafuelcompat
archives_base_name=ia-fuel-compat

# Loom
loom_version=1.7-SNAPSHOT

# Java
java_version=21

# IA
immersive_aircraft_version=1.5.2+1.21.1
